### ISSUE TITLE
Close button's background image is not rendered in IE.

### ISSUE THREAD

**Issue by pilyugin** [competentum/cg-dialog#3]
![2016-08-23_111056](https://cloud.githubusercontent.com/assets/2599338/17884712/6ba29b74-6922-11e6-8634-277d6ba23bb9.png)

**Comment by DariaAbdulnasyrova** [comment]
![image](https://user-images.githubusercontent.com/4981819/36414356-0c7de7a6-1633-11e8-97cf-c6db01478b5b.png)
Fixed in 1.0.0
